#!/bin/bash

validate (){

if [ $1 -ne 0 ]
then 
    echo "Nginx $2 Failure"
else
    echo "Nginx $2 Success"
fi

}

userID=$(id -u)

if [ $userID -ne 0 ]
then
    echo "Run with Super user"
    exit 1
else
    echo "Your are super user"
fi

dnf install nginx -y
validate $? Installtion

systemctl enable nginx
validate $? ENable

systemctl start nginx
validate $? Start
